name: startup_namer
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.0
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.4+1
  flare_flutter: ^2.0.1
  modal_progress_hud: ^0.1.3
  fluttertoast: ^3.1.3
  material_search: ^0.2.8
  connectivity: ^0.4.8+1
  firebase_storage: ^3.1.3
  loading_animations: ^2.1.0
  recase: ^3.0.0
  palette_generator: ^0.2.2
  provider: ^4.0.5
  gradient_widgets: ^0.5.2
  image_picker: ^0.6.5+3
  percent_indicator: ^2.1.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/profile.jpg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - weight: 500
